name: amplitude_flutter_example
description: Demonstrates how to use the amplitude_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  amplitude_flutter:
    path: ../

flutter:
  uses-material-design: true
